- name: Auto-Merge Pull Request
  uses: reitermarkus/automerge@v1.5.2
on:
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review