name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge-pom,!do not merge"
          MERGE_REMOVE_LABELS: "auto-merge-pom"
          MERGE_METHOD: "squash"
          MERGE_FILTER_AUTHOR: "georgiydeliya"
          MERGE_COMMIT_MESSAGE: "automatically merged with auto-merge-pom label, auto update for the pom file"